[package]
name = "oxide-gambit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
iyes_loopless = "0.5.1"
bevy-inspector-egui = "0.11.0"

lazy_static = "1.4.0"



[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/MinerSebas/bevy_lint", branch = "main" },
]